### ISSUE TITLE
Wrong /.html URL 

### ISSUE THREAD

**Issue by rafaviana** [PrestaShop/gsitemap#105]
Hello
Sitemap is creating a "ghost" URL that I can't understand where does it come from… on every language there is a url like this: https://www.sitename.com/pt/.html

Anyone with the same issue or any idea how to solve it? 

I'm using PS 1.7.5.0 with Google Sitempa 4.1.0

Thanks!

**Comment by MathiasReker** [comment]
What are you SEO URL settings?

**Comment by rafaviana** [comment]
Please take a look:
![seo urls temosonline](https://user-images.githubusercontent.com/5817213/52164645-5075f580-26fd-11e9-99af-f9b8640a596a.png)

**Comment by MathiasReker** [comment]
Could you try to remove ".html" and try again?

**Comment by MathiasReker** [comment]
from route to products.

**Comment by rafaviana** [comment]
Hi @MathiasReker . Yes it worked, I think the problem is caused because of a 3rd-party module I'm using to remove IDs from URLs, I already contacted the developer to see he can help me.

Thanks!
