### ISSUE TITLE
Cron error with modules

### ISSUE THREAD

**Issue by bm-services** [PrestaShop/gsitemap#112]
Hi,
We encounter error code when modules try to add URLs in sitemap.
Here, it's "Advanced Search 4" module.

`Return code is 255
Error output was:
	PHP Fatal error:  Uncaught PrestaShopException: Dispatcher::createUrl() miss required parameter "id_seo" for route "module-pm_advancedsearch4-seo" in www/classes/Dispatcher.php:808
	Stack trace:
	#0 www/classes/Link.php(953): DispatcherCore->createUrl('module-pm_advan...', '1', Array, false, '', 1)
	#1 www/modules/gsitemap/gsitemap.php(352): LinkCore->getPageLink('module-pm_advan...', NULL, '1')
	#2 www/modules/gsitemap/gsitemap.php(609): Gsitemap->getMetaLink(Array, Array, 0, 8, 0)
	#3 www/modules/gsitemap/gsitemap-cron.php(61): Gsitemap->createSitemap(1)
	#4 {main}
	  thrown in www/classes/Dispatcher.php on line 808
`

It's on PrestaShop 1.7.4.3 et GSitemap module 4.1.0.

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

I did not manage to reproduce the issue with PS 1.7.5.1 and the module GSitemap V4.1.0.
I attached a screenshot.
![sitemap](https://user-images.githubusercontent.com/16067358/56818366-677d3d00-683f-11e9-93e7-6ff5950e0ca4.png)
Could you please try to uninstall then install the module.
Thanks for check and feedback.

**Comment by ecovidasolar** [comment]
Hello,
you have to deactivate the module advanced search 4. You make the sitemap and then you activate the module advance search 4 again.
It is the only way for you to have both modules active.

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

Have you tried to contact the the module author?
Thanks to check with them & feedback.

**Comment by ecovidasolar** [comment]
This answer of module authot:

> this error is due to the "Google Sitemaps" module
> This module try to use a route created by our module without the needed parameters.
> You have to contact the author of gsitemap module
> 
> Cordialement,

**Comment by khouloudbelguith** [comment]
Hi @ecovidasolar,

Thanks for your feedback.
I installed the advanced search module 4 & then I tried to generate the the sitemap & it is OK.
I attached a video record
https://drive.google.com/file/d/1WHZM0BNd7fcYPF3DqwMunHfw9zRvjvFL/view
Thanks to check & feedback

**Comment by bm-services** [comment]
Hi khouloudbelguith,
The problem occurs with the cron and appears in server log but not in back office interface.

**Comment by khouloudbelguith** [comment]
Hi @bm-services,

Thanks for your feedback.
In my case, I checked my log file, but I did not find any error similar to yours => it is OK.
@sarahdib could you please try to reproduce the issue?
Thanks!

**Comment by sarahdib** [comment]
Hi @bm-services 

We think rhis error is not related to PrestaShop Core but the module advanced search 4. 
I advise you to contact directly the contributor. The error indicated that the gsitemap module try to get a value who doesn't exist in the url generated by advanced search.

Thank you

**Comment by bm-services** [comment]
For information, Advanced Search 4 module support answer:
"The error is generated because the GSiteMap module does not care about any parameters that might be needed for the different modules. You will be able to meet the problem with other modules than ours whose controllers have mandatory parameters (as id_seo in our case).
 
In order to easily fix this, you can exclude the controllers for our module (prefixed by "pm_advancedsearch4_") in the GSiteMap configuration. You will avoid this error."
