### ISSUE TITLE
To index all products images

### ISSUE THREAD

**Issue by Fajy** [PrestaShop/gsitemap#24]
Hi,

In my online shop I have products with some other colors. you can see an example here :

http://www.apprentiphotographe.ch/shop/en/funny-t-shirt/413-women-s-or-men-s-funny-t-shirt-fifty-shades-of-beer.html

That would say that I can have up to 8 kind of images for one product. For me it is important to have all these images indexed by google.

is it possible to have all images indexed instead of the cover only ?

Thanks for an answer.

BR
Fajy

**Comment by Mreker** [comment]
This is bad for SEO. In your case, you should add more products with one color per product.

**Comment by Pixep** [comment]
If anyone want a solution, I just submitted a pull request to expose all images from a product #107.
Google will probably find these images, given some time, but I prefer to expose directly the high-resolution picture in the sitemap. In the end it is always difficult to know exactly how the crawling will go, but this can help, with a minimal impact on the server side.

The only drawback I see is that the label of images is the same for a product (i.e. the product's name).

**Comment by elkeselda** [comment]
> If anyone want a solution, I just submitted a pull request to expose all images from a product #107.
> Google will probably find these images, given some time, but I prefer to expose directly the high-resolution picture in the sitemap. In the end it is always difficult to know exactly how the crawling will go, but this can help, with a minimal impact on the server side.
> 
> The only drawback I see is that the label of images is the same for a product (i.e. the product's name).

Hi, great improvement, is there a way how to load the image title and set it as image label(nstead of the products name)?
