### ISSUE TITLE
Memory exhausted

### ISSUE THREAD

**Issue by Ekman** [PrestaShop/gsitemap#26]
We are running Prestashop using the multi shop feature with 3 shops and approximately 5000 products in total. Our environment is running PHP 5.5 with a memory limit of 768 MB. When we're trying to create a sitemap our server runs out of memory. Tried increasing to 1024 MB and the same problem.

**Comment by Casper-O** [comment]
Try look in gsitemap.php on lne 237 the following should be there:
`if ($i <= 25000 && memory_get_usage() < 100000000)`
try change it to this
`if ($i <= 25000 && memory_get_usage() < 50000000)`
or maybe even this:
`if ($i <= 25000 && memory_get_usage() < 25000000)`
It limits the size of the files that you generate and helped us to generate sitemaps for sites with more than 5000 products even with small amount of memory

**Comment by Ekman** [comment]
Thanks for your reply Casper! I'm closing this since Prestashop does not seem to take these issues seriously.

**Comment by Casper-O** [comment]
Did it help you?

**Comment by Ekman** [comment]
I don't know. The issue is no longer relevant for me. Can't remember if we solved it or went with another solution.
