### ISSUE TITLE
Exclude out of stock product

### ISSUE THREAD

**Issue by TarGz** [PrestaShop/gsitemap#30]
- Would it be possible to only include product with quantity superior to 0 ? 
- It could be interesting to get a checkbox "Exclude product out of stock".
- Even if it's not a feature that could be added could you tell me how I could acheive to modify this module to only add product that are actualy in stock ?

Thanks

**Comment by Mreker** [comment]
This is bad for SEO.

**Comment by Mreker** [comment]
Google win still index all your products even if the products that are out of stock is not in the sitemap.xml :-)
