### ISSUE TITLE
gsitemap 3.2.1 link always wrong

### ISSUE THREAD

**Issue by Repitol** [PrestaShop/gsitemap#39]
Hi
On every Prestashop websites I use, when I enable gsitemap, it displays a link to sitemap which is wrong -> error 404
example
_Please set up the following Sitemap URL in your Google Webmaster account:
http://www.mydomain.com/1_index_sitemap.xml_
This link is definitively wrong so I can't set it up in my Google Search Console
I'm using Prestahop 1.6.11
Any fix ?
Thanks

**Comment by Mreker** [comment]
Thank you for your report! This issue is fixed here: https://github.com/PrestaShop/gsitemap/pull/53
