### ISSUE TITLE
Cron job does not work with Prestashop 1.7

### ISSUE THREAD

**Issue by gfrenoy** [PrestaShop/gsitemap#43]
In "gsitemap-cron.php", the use of p() at line 55 causes a "PHP Fatal error:  Uncaught Error: Call to undefined function p()".

**Comment by chellem** [comment]
Created a pull request (#44) for this. 👍

**Comment by edgarass40** [comment]
Prestashop 1.7
I'm getting 500 error in gsitemap link for cron jobs. 
UndefinedFunctionException in gsitemap-cron.php line 55:
Attempted to call function "p" from the global namespace.
Removing function p like in pull request #44 does not help, then i recieve 500 error without any errors.

**Comment by Mreker** [comment]
Thank you for your report! This issue is fixed here: https://github.com/PrestaShop/gsitemap/pull/53
