### ISSUE TITLE
Timeout on shared hosting

### ISSUE THREAD

**Issue by PR0SAT** [PrestaShop/gsitemap#46]
2233 products x 4 languages + categories + blog module is time and resource consuming (approx. 65 sec for one language) even under php 7 with LiteSpeed server, the whole process should be done faster without the need of creating the whole product object instance if the link_rewrite field is present in my opinion.

All right then, I decied to make an edit:

There is a $_GET['continue'] param which can be used in the cron version to complete the failed timeout task.

**Comment by centoasa** [comment]
dump($gsitemap->createSitemap((int)$id_shop));
also with this at the end of generation file, I've 503 server error

**Comment by Mreker** [comment]
Thank you for your report! This issue is fixed here: https://github.com/PrestaShop/gsitemap/pull/53
