### ISSUE TITLE
 has format errors

### ISSUE THREAD

**Issue by devnetto** [PrestaShop/gsitemap#47]
we have Semrush and there tools says that the sitemap has format error.  they say 
The order should be as listed on https://www.sitemaps.org/protocol.html:

   <url>

      <loc>http://www.example.com/</loc>

      <lastmod>2005-01-01</lastmod>

      <changefreq>monthly</changefreq>

      <priority>0.8</priority>

   </url>

**Comment by Mreker** [comment]
Thank you for your report! This issue is fixed here: https://github.com/PrestaShop/gsitemap/pull/53
