### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by mouse100** [PrestaShop/gsitemap#48]
I've installed the module on my prestashop 1.6.1.17 italian site but I can see the sitemap only in english as in the attached photo. How can I solve?
![26756789_1770472366338917_1479125160348017724_o](https://user-images.githubusercontent.com/35471262/34964523-4b212442-fa4e-11e7-8308-10a3255a3e0b.jpg)

**Comment by Mreker** [comment]
Thank you for your report! This issue is fixed here: https://github.com/PrestaShop/gsitemap/pull/53
