### ISSUE TITLE
Prestashop 1.7 sitemap removed after cron

### ISSUE THREAD

**Issue by samvh13** [PrestaShop/gsitemap#49]
Hi,

after manually making de sitemap, (because a cron job doesn't work) when clicking on the given link, the sitemap is removed. the sitemap-index file still remain's but until i upload a sitemap manualy, there is nothing happening.
What can it be?

with kind regards
sam

**Comment by sanctusmob** [comment]
From Prestaforum

https://www.prestashop.com/forums/topic/606126-google-xml-sitemap-for-prestashop-171/?do=findComment&comment=2781678

Just for everyone else having trouble in the 1.7 version. The gsitemap-cron.php file uses a deprecated debug function "p()". 

You have to change the last line from 

p($gsitemap->createSitemap((int)$id_shop));

to

dump($gsitemap->createSitemap((int)$id_shop));

**Comment by centoasa** [comment]
Also with this, at the end of generation file, I've always 503

**Comment by Mreker** [comment]
Fixed in latest version.
