### ISSUE TITLE
Link to id_category=2 - Category not found

### ISSUE THREAD

**Issue by nndnewbie** [PrestaShop/gsitemap#50]
In sitemap there is link to id_category=2 (`<![CDATA[ https://www.domain.com/2-...`) but that link is not found in Prestashop 1.6.1.x so it generates an error in Google Search Console.

**Comment by HartLarsson** [comment]
on Google sitemap v3.2.2 the error is present:
it generates "2-home" for each language installed!
2-home not exist and give 404 error on Google search console.
There are many bug report on the forge like: http://forge.prestashop.com/browse/PNM-3890
but no one fixed it

**Comment by Mreker** [comment]
Thank you for your report! This issue is fixed here: https://github.com/PrestaShop/gsitemap/pull/53
