### ISSUE TITLE
automatic cancellation of sub-sitemaps

### ISSUE THREAD

**Issue by ghost** [PrestaShop/gsitemap#51]
Good morning

I installed the gsitemap v3.2.2 module in my prestashop 1.7.1.2. The problem is that after generating the sub-sitemaps (divided by language) they are deleted after about half an hour. I tried to edit the file gsitemap-chron.php leave the option p (), deleting the option (p) and replacing with the dump command but in any case the sub-sitemaps are deleted and only the sitemap index and the sitemap in Spanish. How can I solve?

Thank you

**Comment by Mreker** [comment]
This issue is already fixed.
