### ISSUE TITLE
problem with the generated sitemap files

### ISSUE THREAD

**Issue by r-liciotti** [PrestaShop/gsitemap#57]
With the linux cron, the gsitemap module generates only one xml file.
If I use the form or I directly click on the URL that gives me gsitemap then it creates all 5 files.

Prestashop 1.7.3

**Comment by r-liciotti** [comment]
now also with version 4.0.0 of gsitemap it does not work by clicking with the button(it create one only file)

**Comment by Mreker** [comment]
That works for me, for both conjob and button. I uploaded a video here, so you can see it: https://ufile.io/e3b31

**Comment by Mreker** [comment]
Please try to uninstall your old module and reinstall the new module.

**Comment by Mreker** [comment]
Also please send a video to show me your issue.

**Comment by r-liciotti** [comment]
My problem is that with crone task only one sitemap.xml is created, I have already tried to install and reinstall the various versions of gsitemap.


I hope you will understand, thanks vary much!

<img width="1207" alt="schermata 2018-10-19 alle 00 14 28" src="https://user-images.githubusercontent.com/35048026/47187336-f874d800-d333-11e8-88b9-c5be9808f728.png">

**Comment by Mreker** [comment]
I am not able to reproduce your issue.

**Comment by PrestaShark** [comment]
4.0.0 works in 1.7.4.3 without any problem.

**Comment by MathiasReker** [comment]
@r-liciotti can you reproduce on a fresh install?
