### ISSUE TITLE
Schema issue on gsitemap.php

### ISSUE THREAD

**Issue by IT-Droid** [PrestaShop/gsitemap#58]
Hi,

There is an error on generated index_sitemap file, line 732 on gsitemap.php
`        $xml = '<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="**https:**//www.sitemaps.org/schemas/sitemap/0.9"></sitemapindex>';`
google search console needs http not https.

**Comment by MathiasReker** [comment]
Fixed here: https://github.com/PrestaShop/gsitemap/pull/60

**Comment by MathiasReker** [comment]
Please close this issue.

**Comment by Quetzacoalt91** [comment]
Fixed by #60
