### ISSUE TITLE
Main store category is not needed in sitemap

### ISSUE THREAD

**Issue by PrestaShark** [PrestaShop/gsitemap#59]
Main store category is not needed in sitemap IMHO. Need to remove it.

**Comment by MathiasReker** [comment]
Can you point it out on a screenshot. I am not 100% sure what you mean?

**Comment by MathiasReker** [comment]
Ok, you mean the home category. I make a PR for that.

**Comment by MathiasReker** [comment]
Fixed here: https://github.com/PrestaShop/gsitemap/pull/61

**Comment by PrestaShark** [comment]
Works like a charm :) Thank You

**Comment by MathiasReker** [comment]
You are welcome

**Comment by MathiasReker** [comment]
Please close this issue.

**Comment by Quetzacoalt91** [comment]
Fixed by #61
