### ISSUE TITLE
presta 1.7.2

### ISSUE THREAD

**Issue by sajjads3** [PrestaShop/gsitemap#62]
hi tanx for your work
i use presta 1.7.2 and sitemap dosen include id_product_attribute

my structure on presta 1.7.2 is
{id}{-:id_product_attribute}/{rewrite}

and
product in my website like :
https://www.example.com/fa/33-98/productname

and in sitemap like : 
https://www.example.com/fa/33/namekala

because prestashop 1.7 i have to use id_product_attribute but sitemap not making it
pls help me
tanx

**Comment by MathiasReker** [comment]
I am not able to solve this, sorry. Why would you want to make a path of ID's? It is not good for SEO.
