### ISSUE TITLE
Duplicating main page

### ISSUE THREAD

**Issue by evgenij-sobolev** [PrestaShop/gsitemap#63]
I have issue with dublicating the main page:

![screenshot_1](https://user-images.githubusercontent.com/20418648/47955110-96ef7300-df9b-11e8-9b73-2b3a12de2070.png)

Prestashop 1.6.1.20
gsitemap v3.2.2

**Comment by evgenij-sobolev** [comment]
The same error on version 1.6.1.22 and gsitemap v3.2.2

**Comment by evgenij-sobolev** [comment]
> 
> 
> Fixed in gsitemap v4, but you can not install v4 on PS 1.6. You need to upgrade your PS to 1.7.x.

Bad news.
Maybe you can apply this fix for version 3.x?
It is still a very large number of stores using version 1.6.x

**Comment by MathiasReker** [comment]
Try to apply this commit: https://github.com/PrestaShop/gsitemap/pull/23/commits/87b70abb12f64ce3fe5131c4450b850263059054

**Comment by evgenij-sobolev** [comment]
Thank you, but it did not help.

**Comment by MathiasReker** [comment]
Weird. Did you regenerate the sitemaps?
