### ISSUE TITLE
it stops in the middle of generate sitemap. v4.0 with presta 1.7

### ISSUE THREAD

**Issue by nbexiga** [PrestaShop/gsitemap#65]
Hi
i had to roll back to the v.2.3.3 because when i generated the sitemap with version 4.0 it disappear from the sitemap module, go to the main modules page , and if i return to the sitemap module to generate i noticed that it was not generated any file only one part of the sitemap.
it does not complete the task.
if i run by cron the same issue.
where i can see the logs for this? or where is the problem?
thanks

**Comment by khouloudbelguith** [comment]
Hi @nbexiga,

If you click on the "Generate sitemap" button, there is no sitemap file generated?
I attached a video record
https://drive.google.com/file/d/1i-YDyzVvklUmRqwC21CUFxEhtxvLxOT2/view
Thanks!

**Comment by nbexiga** [comment]
Hi
if i click generate sitemap it keeps loading but after that it goes to the main menu for the modules... 
and no sitemap generated..
in the version before it was generated 5 langs of my store in separate files... and one sitemap generated..

**Comment by khouloudbelguith** [comment]
@nbexiga, I did not manage to reproduce the issue with 1.7.4.4 / 1.7.5.0beta1 & the gsitemap module v4.0.0 as I attached in the video record.
You can enable the debug mode & paste here the exceptions that you have.
Thanks!

**Comment by khouloudbelguith** [comment]
@nbexiga, thanks!
Waiting for your feedback.

**Comment by nbexiga** [comment]
With the debug mode activated it does not give any error ...
:(
after i click generate sitemap it loads for 2 minutes +- and after that go to the modules pagae again.

when i return to the module only generated one part ..
see atached print
![sitemap](https://user-images.githubusercontent.com/34128424/48481716-75498380-e806-11e8-8c08-10564c9dc911.JPG)

**Comment by khouloudbelguith** [comment]
@nbexiga, We need to retrieve the PHP error log in order to find out what's wrong.

**Comment by nbexiga** [comment]
How can i get the php error? 
in the log does not appear nothing.. :(
where is other log?

**Comment by nbexiga** [comment]
maybe this? i found in the log regarding sitemap

[Wed Nov 14 12:16:12.116459 2018] [proxy_fcgi:error] [pid 2439:tid 139850669795072] [client 173.249.46.227:37336] AH01068: Got bogus version 111, referer: https://tngoodies.com/tempftrol/index.php?controller=AdminModules&configure=gsitemap&token=7f62f408f295c9aef05aa1cf9290db62

**Comment by nbexiga** [comment]
and how can i see the error log for this? for the module

**Comment by khouloudbelguith** [comment]
@nbexiga, you can follow this [link](http://build.prestashop.com/howtos/misc/how-to-create-bug-report/) to get how can add logs.
Thanks!

**Comment by nbexiga** [comment]
that0s the only thing that i have in php errors :(

**Comment by khouloudbelguith** [comment]
Hi @nbexiga,

I tried with version Prestashop 1.7.4.3, but I did not manage to reproduce the issue.
https://drive.google.com/file/d/1-mt4vlDvpr5yfKEMuQhnPsH7PGyVtKfk/view
Thanks!

**Comment by nbexiga** [comment]
i have the store in 5 languages.. can be because of that? 
many products?

**Comment by khouloudbelguith** [comment]
@nbexiga, no.
I have more than 5 languages & it is Ok.
![image](https://user-images.githubusercontent.com/16067358/48491345-a38b8b00-e827-11e8-8be4-ba3c01715b61.png)

**Comment by nbexiga** [comment]
so what can be the problem with me? please help.. :)

**Comment by marionf** [comment]
I can't reproduce either

**Comment by nbexiga** [comment]
for me it's not any error that gives...
simply get out of the module and go to the main modules installed page...
