### ISSUE TITLE
Image caption does not insert space between paragraphs

### ISSUE THREAD

**Issue by pvechi** [PrestaShop/gsitemap#67]
I assume caption is taken from the product's brief description.  If I have two paragraphs `<p>` on the brief description, the caption appearing on the sitemap does not insert a space between the paragraphs.

Eg. The sitemap image caption shows "... end of my first paragraph.Start of next paragraph ..." instead of "... end of my first paragraph. Start of next paragraph ..."

Sentences within a paragraph do show spaces.

[See this example](https://www.prosacalwaysmile.com/1_en_0_sitemap.xml)

**Comment by MathiasReker** [comment]
Fixed: https://github.com/PrestaShop/gsitemap/pull/68

**Comment by MathiasReker** [comment]
Please close this issue.

**Comment by pvechi** [comment]
Thanks @MathiasReker for looking into this.  How do I check this?  Is an update available via Prestashop addons or our backoffice?  Thanks again.

**Comment by MathiasReker** [comment]
@pvechi you have to edit your module from ftp.

**Comment by pvechi** [comment]
@MathiasReker will this be included on the next update from Prestashop Addons?

**Comment by PierreRambaud** [comment]
Thanks @pvechi and @MathiasReker for the pull request. I'm agree with the change, don't know what think other developers. We will close this issue once the PR will be merge :)
