### ISSUE TITLE
Do not work with SimpleBlog

### ISSUE THREAD

**Issue by astagi** [PrestaShop/gsitemap#69]
I can't include articles in sitemap, I'm using SimpleBlog module. Any hint?

**Comment by burrots** [comment]
Yo can't include pages in sitemap from other modules. This module is only for prestashop native pages...

**Comment by marionf** [comment]
Gsitemap is only for prestashop native pages

**Comment by astagi** [comment]
Thanks @marionf

**Comment by MathiasReker** [comment]
@marionf It should be possible for a non-native module to include itself. The module will become visible in the configuration and should be unchecked to be included in the sitemap. I think the SimpleBlog maybe has an issue. Maybe this should stay open for a while?

@astagi Can you send a screenshot of your configuration?

**Comment by astagi** [comment]
Hi @marionf this is my configuration:

![image](https://user-images.githubusercontent.com/537363/49501278-c501f480-f872-11e8-84bb-cb302c91fede.png)

I tried to search something related to SimpleBlog exportation but I didn't find anything

**Comment by MathiasReker** [comment]
@astagi Can you please contact SimpleBlog? I think they may have an issue.

**Comment by MathiasReker** [comment]
Not a PrestaShop issue. I asked the develop of SimpleBlog to look into this. Please close this PR :-)
