### ISSUE TITLE
Index sitemap file generated with errors

### ISSUE THREAD

**Issue by omata** [PrestaShop/gsitemap#70]
**Prestshop version:** 1.7.4.2
**PHP version:** 7.2.12
**Google Sitemap module version:** 4.0.0

When I generate the sitemap with the button it is build. But the sitemap index return errors when tested at Google sitemap. The error is related with a wrong space in the name, Google says that expected is, *(line 2)*:
```
http://www.sitemaps.org/schemas/sitemap/0.9
```
And found is:
```
https://www.sitemaps.org/schemas/sitemap/0.9
tag: sitemapindex
```
I don't know if it is related with the site certificate, even if the URL with `https://` protocol is reachable without issues.

I didn't found errors in each sitemap file generated for each language.

Best regards.

**Comment by MathiasReker** [comment]
Solved here: https://github.com/PrestaShop/gsitemap/pull/60
