### ISSUE TITLE
Unable to Install on Prestashop 1.6.1.23

### ISSUE THREAD

**Issue by razarahil** [PrestaShop/gsitemap#75]

**Comment by MathiasReker** [comment]
You need at least PS 1.7.1.x to use v. 4.0.x of the module. You can use v. 3.x.x for PS 1.6.1.23

**Comment by khouloudbelguith** [comment]
Hi @razarahil,

As @MathiasReker said, gsitemap module is compatible with PS1.7.1.0 or more.
https://github.com/PrestaShop/gsitemap/blob/v4.0.0/gsitemap.php#L48
Thanks!

**Comment by khouloudbelguith** [comment]
@razarahil, thanks to check with this file.
[gsitemap.zip](https://github.com/PrestaShop/gsitemap/files/2662778/gsitemap.zip)
Thanks!
