### ISSUE TITLE
Google Search Console says: Incorrect namespace

### ISSUE THREAD

**Issue by acaparrelli** [PrestaShop/gsitemap#76]
I'm using PS 1.7.4.2

As I say in the subject Google Search Console returns these errors:

- Sitemap index can be read, but has errors
- Your Sitemap or Sitemap index file doesn't properly declare the namespace. Line: 2

The problem is only with the Index, the child sitemaps (one for each language) seems to be accepted correctly.

**Comment by MathiasReker** [comment]
Fixed here: https://github.com/PrestaShop/gsitemap/pull/60
